// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kstmkemqewgdwwedcwsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzdG1rZW1xZXdnZHd3ZWRjd3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDYwODEsImV4cCI6MjA1OTU4MjA4MX0.8O8J1XkOg8SKcKrtP6jFmQrS2weMRJkzAuGgNkSBD-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);